name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        edge:
          - true
          - false
        gemfile:
          - Gemfile
          - Gemfile.edge
        image:
          - ruby:2.4.0
          - ruby:2.4
          - ruby:2.5.0
          - ruby:2.5
          - ruby:2.6.0
          - ruby:2.6
          - ruby:rc
          - jruby:9.2
        include:
          - image: ruby:rc
            continue-on-error: true
          - gemfile: Gemfile.edge
            continue-on-error: true
    container: ${{matrix.image}}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        run: |
          gem update --system > /dev/null
          gem --version
          gem i bundler
          bundler install --gemfile=${{matrix.gemfile}}
      - name: Run tests
        run: bundler exec rake
