name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - Gemfile.edge
        image:
          - image: ruby
            tag: 2.4.0
          - image: ruby
            tag: "2.4"
          - image: ruby
            tag: 2.5.0
          - image: ruby
            tag: "2.5"
          - image: ruby
            tag: 2.6.0
          - image: ruby
            tag: "2.6"
          - image: ruby
            tag: rc
          - image: jruby
            tag: "9.2"
        include:
          - image:
              image: ruby
              tag: rc
            continue-on-error: true
          - gemfile: Gemfile.edge
            continue-on-error: true
    container: ${{matrix.image.image}}:${{matrix.image.tag}}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        run: |
          gem update --system > /dev/null
          gem --version
          gem i bundler
          bundler install --gemfile=${{matrix.gemfile}}
      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{matrix.gemfile}}
        run: bundler exec rake
      - name: Upload manuals
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Manual (${{matrix.image.image}}-${{matrix.image.tag}}, ${{matrix.gemfile}})
          path: test-manual.pdf
