name: Manual

on: push

jobs:
  Manual:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - Gemfile.edge
    container: ruby:latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        run: |
          gem update --system > /dev/null
          gem --version
          gem i bundler
          bundler install --gemfile=${{matrix.gemfile}}
      - name: Build manual
        env:
          BUNDLE_GEMFILE: ${{matrix.gemfile}}
        run: bundler exec rake manual
      - name: Upload manula
        uses: actions/upload-artifact@v1
        with:
          name: manual
          path: manual.pdf
